# Generated by Django 5.1.7 on 2025-04-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_display_name_user_joined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_job',
            field=models.TextField(blank=True, null=True),
        ),
    ]
